### ISSUE TITLE
Why was v0.2.4 deleted?

### ISSUE THREAD

**Issue by matiboux** [mkhorasani/Streamlit-Authenticator#110]
Hello,
My application failed to deploy today because it relied on the latest 0.2.4 release after adapting the code yesterday for it.
I noticed the v0.2.4 release was deleted here on GitHub and on PyPI.

Can I ask why this happened?
Why not release 0.2.5 with required fixes or reverts to changes?

**Comment by mkhorasani** [comment]
Hi @matiboux, apologies for the inconvenience, however, due to an influx of issues being raised by developers, I decided to delete v0.2.4 and work on a new version with a deprecation warning to prompt developers to adjust their code accordingly. This is my mistake as I assumed that the readme would be enough of a prompt. I will try to release v0.2.5 within a few days to rectify this problem. Thank you for your patience.

**Comment by matiboux** [comment]
> Please feel free to download it.

Thank you @mkhorasani! I will look into it!
