### ISSUE TITLE
session_state["authentication_status"] latency issues    

### ISSUE THREAD

**Issue by wyzdic** [mkhorasani/Streamlit-Authenticator#124]
with st.sidebar.container():
    with open('config.yaml', encoding='utf-8') as file:
        config = yaml.load(file, Loader=SafeLoader)

    authenticator = stauth. Authenticate(
        config['credentials'],
        config['cookie']['name'],
        config['cookie']['key'],
        config['cookie']['expiry_days'],
        config['preauthorized']
    )

if not st.session_state["authentication_status"]:
  authenticator.login()
if st.session_state["authentication_status"]:
  st.write('here)
elif st.session_state["authentication_status"] is False:
  st.error()
elif st.session_state["authentication_status"] is None:
  st.warning()

When I use this code structure, if I refresh or reopen the page when I am logged in, the login page will appear first, and then it will be rendered as the logged in page again.
Checking the data with st.write(session_state["authentication_status"]) reveals that the value is None and then updated to True, which is the problem
Now I'm in authenticator=stauth. Adding time.sleep(0.2) to the end of the Authenticate snippet temporarily solves the problem, is there a better solution?

**Comment by mkhorasani** [comment]
Hi @wyzdic, the issue here is that when you refresh your Streamlit application, all session state variables are reset by default, including the **authentication_status** variable, so effectively you are logged out when you refresh. However, given that Streamlit-Authenticator stores a reauthentication cookie on your browser, each time you rerun, the cookie is checked against your config file cookie parameters to log you back in automatically. However the implementation is somewhat slow due to the cookie manager taking its time to read the cookie. I like your approach and will reconsider adding it to a future release.

**Comment by mkhorasani** [comment]
Can you please share a short video or gif of the problem?

**Comment by mkhorasani** [comment]
Dear all please refer to the latest release [v0.3.2](https://github.com/mkhorasani/Streamlit-Authenticator/releases/tag/v0.3.2).
